### ISSUE TITLE
Tagtagtag sound card driver incompatibility with latest versions of 5.15 and 6.1 kernel

### ISSUE THREAD

**Issue by f-laurens** [pguyot/wm8960#21]
See https://www.tagtagtag.fr/forum/showthread.php?tid=467&pid=2541#pid2541

Tagtagtag sound card driver, which worked fine with kernel version 5.15.32 (20220331), seems incompatible with later versions (5.15.56, 5.15.61, 5.15.76, 5.15.84, 6.1.21, ...):

Following kernel upgrade, after Pynab drivers recompilation (which works fine) and reboot:

- rabbit is mute
- nabd log shows a problem configuring sound card:
```
pi@Nabaztag:~$ cat /var/log/nabd.log
2022-08-31 14:38:55,088 [INFO] nabd: started with log level INFO
2022-08-31 14:38:55,500 [ERROR] nabd: Unable to configure sound card for playback
2022-08-31 14:38:55,504 [WARNING] nabd: no Tagtagtag card?
2022-08-31 14:38:55,542 [ERROR] nabd: Unable to configure sound card for playback
2022-08-31 14:38:55,543 [WARNING] nabd: no sound card?
2022-08-31 14:38:55,567 [INFO] nabd: running on Raspberry Pi Zero W Rev 1.1
```

- the following errors appear for the sound driver:

```
pi@Nabaztag:~$ dmesg | grep wm8960
[   31.610013] wm8960 1-001a: failed to configure clock
[   31.610043] wm8960 1-001a: ASoC: error at snd_soc_dai_hw_params on wm8960-hifi: -22
[   31.610072]  bcm2835-i2s-wm8960-hifi: ASoC: soc_pcm_hw_params() failed (-22)
[   31.651845] wm8960 1-001a: failed to configure clock
[   31.651876] wm8960 1-001a: ASoC: error at snd_soc_dai_hw_params on wm8960-hifi: -22
[   31.651904]  bcm2835-i2s-wm8960-hifi: ASoC: soc_pcm_hw_params() failed (-22)
```

**Comment by pguyot** [comment]
Actually the problem is not the compatibility of the driver with later kernel but rather that you try to use the wm8960 driver provided by your Linux distribution. The tagtagtag-sound branch contains fixes which I never submitted upstream.

**Comment by f-laurens** [comment]
> you try to use the wm8960 driver provided by your Linux distribution.

Issue is indeed now effectively solved by https://github.com/pguyot/wm8960/commit/b552bdcedb74d162daf2318fc77116b2f209a84e, which fixes tagtagtag-sound driver build/installation procedure.

**Comment by f-laurens** [comment]
@pguyot: it might be useful to create a new tag **v1.0.2** for https://github.com/pguyot/wm8960/commit/b552bdcedb74d162daf2318fc77116b2f209a84e.
