### ISSUE TITLE
Make won't compile

### ISSUE THREAD

**Issue by nodemand** [pguyot/wm8960#23]
I'm on Raspberry Pi OS Bookworm 64 bit and am getting these errors while running `make`:
```
wm8960/wm8960.c:1386:10: error: ‘const struct snd_soc_component_driver’ has no member named ‘non_legacy_dai_naming’; did you mean ‘legacy_dai_naming’?
 1386 |         .non_legacy_dai_naming  = 1,

wm8960/wm8960.c:1499:21: error: initialization of ‘void (*)(struct i2c_client *)’ from incompatible pointer type ‘int (*)(struct i2c_client *)’ [-Werror=incompatible-pointer-types]
 1499 |         .remove =   wm8960_i2c_remove,
      |                     ^~~~~~~~~~~~~~~~~
```

**Comment by f-laurens** [comment]
> I'm on Raspberry Pi OS Bookworm

Then you are probably running a 6.1 kernel.  See https://github.com/pguyot/wm8960/pull/22; it should fix your problem.

**Comment by nodemand** [comment]
@f-laurens sorry, but I don't understand. In #22 you guys talk about compiling that works but it does not run. On my RPi it does not compile. I'm not sure how that is the same issue or how that helps me. Can you please explain?

**Comment by f-laurens** [comment]
Well, that's simple:
- if you apply the fix proposed in https://github.com/pguyot/wm8960/pull/22, the driver should compile;
- but since you are running Bookworm (and hence presumably a 6.1 kernel), the driver will probably not run correctly (see https://github.com/pguyot/wm8960/issues/21).

**Comment by nodemand** [comment]
Ah yes. I see now. Thanx!

**Comment by Tazmaniac** [comment]
As all original modifications needed for wm8960 to work on Tagtagtag are now mainline did you try the mainline kernel with proper overlay ?

**Comment by pguyot** [comment]
@Tazmaniac Unfortunately the module in mainline kernel doesn't work with the Tagtagtag card.
Error reported in #21 can be reproduced by using module from mainline kernel, now shipped with Raspberry Pi OS.
