### ISSUE TITLE
Son grésillant (TagTagTag 2024)

### ISSUE THREAD

**Issue by rubuano** [pguyot/wm8960#26]
Hello, tout d'abord bravo et merci pour le travail effectué sur les projets, c'est cool de découvrir une nouvelle communauté autant investie !

J'ouvre un ticket concernant un souci de lecture qui grésille, sur certains formats. D'après ce que j'ai pu lire à droite à gauche, les problèmes de sons étaient souvent liés au driver audio.

J'ai reçu aujourd'hui une carte du batch 2024, que j'ai configurée et installée en suivant scrupuleusement les instructions. Tout fonctionne parfaitement excepté la lecture audio.

J'ai pris quelques vidéos pour aider au diagnostic :

Lecture de la météo en français, puis en anglais (pas le même comportement!).
En français, seul le mot "degré" est entendu correctement.

https://github.com/pguyot/wm8960/assets/33329579/7649d554-bf9e-4b4d-8fe3-b85d0b0843e0

https://github.com/pguyot/wm8960/assets/33329579/e1e46985-301b-49be-a70a-527ed6b39f12

Dernière vidéo, j'ai lancé deux commandes :
- `speaker-test -c2 -twav -l7` : Audio clair 💯 
- `mpg123 file_example_MP3_1MG.mp3` : Son grésillant (le fichier utilisé est [trouvable ici](https://file-examples.com/storage/fe92070d83663e82d92ecf7/2017/11/file_example_MP3_1MG.mp3)). En dehors des petits bzzz que l'on peut entendre sur toutes les vidéos, un gros bruit blanc reste actif quelques secondes après l'arrêt de la lecture.

https://github.com/pguyot/wm8960/assets/33329579/bc1bdd76-e32f-43c5-9911-5dc6f15af8cf

Concernant ce que j'ai d'installé, voici ce que me liste l'interface Pynab :

![CleanShot 2024-05-14 at 19 02 00@2x](https://github.com/pguyot/wm8960/assets/33329579/6ba42ece-95d3-46c8-9ee7-0b3a61ef3686)

J'ai tenté également de cloner/compiler puis installer la version la plus récente du driver sur la branche tagtagtag-sound, tout le processus se déroule sans souci, les grésillements sont toujours présents.

Je reste à dispo pour effectuer des tests si besoin !

**Comment by pguyot** [comment]
Je me demande si le driver de la carte son est vraiment le problème et d'où vous vient cette idée. 

Est-ce qu'il y a quelque chose de particulier dans les logs ?

Est-ce que vous arrivez à lire des fichiers wav ?

Peut-être que le matériel est défectueux, pourquoi pas la carte SD ou certains fichiers sont endommagés. Avez-vous les mêmes sommes de contrôle sur les mp3 que sur le desktop ?

**Comment by rubuano** [comment]
Hello, merci de votre réponse. 

> Je me demande si le driver de la carte son est vraiment le problème et d'où vous vient cette idée.

Rien de certain ici évidemment, mais compte tenu que tout le reste semple fonctionner correctement et que le problème ne survient que sur certains formats audio, j'ai logiquement ouvert une issue ici.

> Est-ce qu'il y a quelque chose de particulier dans les logs ?

Je n'ai rien vu de particulier dans les logs système, ni dans les fichiers présents dans /var/log. 

-----

En réalisant d'autres tests sur différents fichiers, notamment [ceux de la météo](https://github.com/nabaztag2018/pynab/tree/master/nabweatherd/sounds/fr_FR/nabweatherd), j'ai pu reproduire l'échec de lecture de `today.mp3` et la réussite de `degree.mp3`. 

![telegram-cloud-photo-size-4-5918281689564562807-y](https://github.com/pguyot/wm8960/assets/33329579/9bd8918e-c9c0-485c-a3c5-201c40bbc071)

J'ai immédiatement remarqué les différences, concernant les canaux et le sample rate. Pour isoler ça, j'ai converti `today.mp3`, directement sur le lapin, avec ces deux commandes : 

```
# -ac 1 définit le nombre de de canaux à 1, convertissant la stereo en mono
ffmpeg -i today.mp3 -ac 1 today_mono.mp3

# -ar 32000 définit le taux d'échantillonage à 32kHz
ffmpeg -i today.mp3 -ar 32000 today_32000.mp3
```

Résultats… 🥁 seul le fichier `today_32000.mp3` est entendu clairement. Les autres grésillent.

Maintenant qu'on a isolé ça, je pense qu'on peut écarter certains problèmes de corruption de fichiers ou de mauvais branchements.

En revanche, c'est vous l'expert ! Si le souci n'est pas lié à au driver audio, je peux ouvrir une issue pour faire suite dans le repo de Pynab.

**Comment by pguyot** [comment]
Merci pour ces détails et d'avoir trouvé que le problème se produit avec des sons en 44.1kHz et pas avec ceux en 32kHz.

L'invite "mgk@tagtagtag" de votre photo d'écran ne ressemble pas à ce qu'il y a sur les lapins installés avec [l'image pynab](https://github.com/nabaztag2018/pynab/releases/tag/v1.0.2). Pouvez-vous m'en dire plus sur votre système ?

**Comment by rubuano** [comment]
Pour l'installation j'ai utilisé l'image de la dernière pynab. Avec l'outil Raspberry Pi Imager, j'ai configuré avant l'écriture sur la carte SD :
- le compte utilisateur/mot de passe 
- activé le SSH et l'authentification par clé
- défini le hostname sur "tagtagtag"

**Comment by pguyot** [comment]
Est-ce que vous pouvez redémarrer le lapin puis lancer un son qui ne marche pas (today.mp3), puis faire `dmesg` et coller ici le log depuis 0.000000 ?

**Comment by rubuano** [comment]
Voici le log. Il ne semble pas y avoir de message suite à la lecture du son.

[dmesg.txt](https://github.com/pguyot/wm8960/files/15318439/dmesg.txt)

**Comment by pguyot** [comment]
Merci. Je pense qu'il ne faut pas éliminer la possibilité d'un problème matériel de votre carte. Votre log n'indique rien de suspect, le driver n'a pas l'impression qu'il y a la moindre erreur. Et il fonctionne normalement selon toutes les fréquences d'échantillonage standard. Il est néanmoins possible qu'il y ait un problème avec son horloge qui fait que ça ne marche qu'en mono 32kHz. Est-ce que vous avez essayé d'autres fréquences ? Les fréquences standard gérées par le chipset sont 8k, 11.025k, 16k, 22.050k, 32k, 44.1k et 48k.

**Comment by rubuano** [comment]
Merci pour les précisions techniques.

> [...] ne marche qu'en mono 32kHz. 

Précision, la stereo fonctionne également, le fichier `today.mp3` dispose de deux canaux.

Voici les résultats, tests effectués en convertissant le fichier `today.mp3` d'origine :

- 8k: OK
- 11.025k: KO
- 16k: OK
- 22.050k: KO
- 32k: OK
- 44.1k: KO
- 48k: OK

Très curieux !

**Comment by pguyot** [comment]
C'est plutôt conforme à ce que j'attendais. La fréquence d'horloge est de 12MHz, soit un multiple de toutes les fréquences qui fonctionnent. Je vous invite à contacter Olivier pour voir si le problème vient de la carte.

**Comment by rubuano** [comment]
Bonjour !

Toutes mes excuses, le son venait en effet d'un défaut de matériel. Mon lapin s'exprime correctement à nouveau 🐰

Merci pour le diagnostic et votre réactivité :)

Je ferme l'issue.
